sudo: false
language: node_js
node_js:
  - "4.2"
os:
  - linux
  #- osx
before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi;
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install pkg-config exiv2; fi;
  # Because they say that osx does not support node_js
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install homebrew/versions/node4-lts; fi;

# See https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
  apt:
    packages:
      - libexiv2-11
      - libexiv2-dev
matrix:
  fast_finish: true
  #allow_failures:
  #  - os: osx
