# https://docs.travis-ci.com/user/sonarcloud/ requires to use trusty
# https://github.com/travis-ci/apt-package-safelist/blob/master/ubuntu-trusty
dist: trusty

addons:
  apt:
    packages:
      - exiv2
      - libexiv2-dev
  sonarcloud:
    organization: "paazmaya-github"
    token:
      secure: $SONAR_TOKEN

language: node_js
node_js:
  - "10"
  - "12"

script:
  - sonar-scanner -Dsonar.projectVersion=$TRAVIS_COMMIT -Dsonar.links.scm=https://github.com/paazmaya/kanigawa/tree/$TRAVIS_COMMIT
  - npm test
matrix:
  fast_finish: true

# Deploy to GitHub Pages
before_deploy:
  - npm run build
  - npm run analyze
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: master
