# https://docs.travis-ci.com/user/sonarcloud/
dist: trusty # Sonarcloud requirement
addons:
  # See https://github.com/travis-ci/apt-package-safelist/blob/master/ubuntu-trusty
  apt:
    packages:
      - exiv2
      - libexiv2-dev
  sonarcloud:
    organization: "paazmaya-github"
    token:
      secure: $SONAR_TOKEN
after_install:
  - sonar-scanner

language: node_js
node_js:
  - "10"
os:
  - linux
  #- osx
before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi;
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install pkg-config exiv2; fi;
  # Because they say that osx does not support node_js
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install homebrew/versions/node4-lts; fi;

matrix:
  fast_finish: true
  #allow_failures:
  #  - os: osx
