# https://github.com/travis-ci/apt-package-safelist/blob/master/ubuntu-trusty
dist: trusty

addons:
  apt:
    packages:
      - exiv2
      - libexiv2-dev

language: node_js
node_js:
  - "10"
  - "12"

script:
  - npm test
matrix:
  fast_finish: true

# Deploy to GitHub Pages
before_deploy:
  - npm run build
  - npm run analyze
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: master
