language: node_js
node_js:
  - "4.2"
  - "5"
os:
  - linux
  - osx
before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libexiv2 libexiv2-dev; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install pkg-config exiv2; fi;
matrix:
  fast_finish: true
	allow_failures:
    - os: osx
