environment:
  matrix:
    - nodejs_version: "12"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  # Download exiv2 and make available in "Path"
  # https://www.exiv2.org/builds/exiv2-0.27.1-msvc64.zip
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# TODO: Test Electron working around the React app

# Don't actually build.
build: "off"

matrix:
  fast_finish: true
